openapi: "3.0.2"
info:
  title: "Vert.x Web API contract and service example"
  description: "Lorem ipsum..."
  version: "1.0"
  termsOfService: "https://whatever.org/terms"
  contact:
    name: "Whoever"
    url: "https://whatever.org/contact"
    email: "some_email@whatever.com"
  license:
    name: "Lorem ipsum..."
    url: "https://openweathermap.org/license"
servers:
  - url: "http://localhost:8080/api/v1.0"
    description: "Testing"
paths:
  /json:
    post:
      tags:
      - Upload JSON document
      summary: "Lorem ipsum..."
      description: "Lorem ipsum..."
      operationId: uploadJSON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  format: email
                to:
                  type: string
                  format: email
              required:
                - from
                - to
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  from:
                    type: string
                    format: email
                  to:
                    type: string
                    format: email
                required:
                  - from
                  - to
      x-vertx-event-bus:
        address: testService
        method: uploadJson
  /pdf:
    post:
      tags:
      - Create new PDF document
      summary: "Lorem ipsum..."
      description: "Lorem ipsum..."
      operationId: uploadPdf
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: "application/pdf"
                headers:
                  Content-Disposition:
                    description: "Lorem ipsum"
                    schema:
                      type: string
                      enum: ["form-data"]
                  filename:
                    description: "Lorem ipsum"
                    schema:
                      type: string
      responses:
        201:
          description: Doc created
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  placeholder:
                    type: string
                    description: Placeholder description
      x-vertx-event-bus:
        address: testService
        method: uploadPdf

